@startuml

'!theme plain
top to bottom direction
'skinparam linetype ortho

interface AliasRegistry
class SimpleAliasRegistry
interface SingletonBeanRegistry
class DefaultSingletonBeanRegistry
class FactoryBeanRegistrySupport

interface BeanFactory
interface HierarchicalBeanFactory
interface ListableBeanFactory
interface ConfigurableBeanFactory
interface ConfigurableListableBeanFactory
interface AutowireCapableBeanFactory

class AbstractBeanFactory
interface BeanDefinitionRegistry
class AbstractAutowireCapableBeanFactory
class DefaultListableBeanFactory



note top of AliasRegistry:<red>定义了对 alias 的简单增删改查等操作</red>
note top of BeanDefinitionRegistry: 定义对 BeanDefinition 的各种增删改查操作
note left of SimpleAliasRegistry:主要使用 map作为alias的缓存，\n并对接口 AliasRegistry进行实现
note top of SingletonBeanRegistry:定义对单例bean的注册及获取
note left of DefaultSingletonBeanRegistry:对接口 SingletonBeanRegistry 各函数的实现
note left of FactoryBeanRegistrySupport:在DefaultSingletonBeanRegistry 基础上\n增加了对 FactoryBean 的特殊处理功能

note top of BeanFactory:定义获取 bean 及 bean 的各种属性
note top of ListableBeanFactory:根据各种条件获取 bean 的配置清单
note top of HierarchicalBeanFactory:在 BeanFactory 定义的功能基础上\n增加了对 parentFactory 的支持
note top of ConfigurableBeanFactory: 提供配置 Factory 的各种方法
note right of AutowireCapableBeanFactory: 提供创建bean、自动注入、初始化\n以及应用 bean 的后置处理器
note left of AbstractBeanFactory: 综合 FactoryBeanRegistrySupport 和\nConfigurableBeanFactory 的功能
note right of ConfigurableListableBeanFactory: BeanFactory 配置清单，指定忽略类型及接口
note left of AbstractAutowireCapableBeanFactory: 综合 AbstractBeanFactory 并对接口 \nAutowireCapableBeanFactory 进行实现


note right of DefaultListableBeanFactory: 综合上面所有功能，主要是对 bean 注册后的处理


AbstractBeanFactory          ^-[#000082,plain]-     AbstractAutowireCapableBeanFactory
AutowireCapableBeanFactory  ^-[#008200,dashed]-    AbstractAutowireCapableBeanFactory
ConfigurableBeanFactory     ^-[#008200,dashed]-    AbstractBeanFactory
FactoryBeanRegistrySupport   ^-[#000082,plain]-     AbstractBeanFactory
BeanFactory                  ^-[#008200,plain]-     AutowireCapableBeanFactory
AliasRegistry                ^-[#008200,plain]-     BeanDefinitionRegistry
HierarchicalBeanFactory      ^-[#008200,plain]-     ConfigurableBeanFactory
SingletonBeanRegistry        ^-[#008200,plain]-     ConfigurableBeanFactory
AutowireCapableBeanFactory   ^-[#008200,plain]-     ConfigurableListableBeanFactory
ConfigurableBeanFactory      ^-[#008200,plain]-     ConfigurableListableBeanFactory
ListableBeanFactory          ^-[#008200,plain]-     ConfigurableListableBeanFactory

AbstractAutowireCapableBeanFactory      ^-[#000082,plain]-   		DefaultListableBeanFactory
BeanDefinitionRegistry         					^-[#008200,dashed]-     DefaultListableBeanFactory
ConfigurableListableBeanFactory         ^-[#008200,dashed]-     DefaultListableBeanFactory
SimpleAliasRegistry       							^-[#000082,plain]-      DefaultSingletonBeanRegistry
SingletonBeanRegistry        						^-[#008200,dashed]-     DefaultSingletonBeanRegistry
DefaultSingletonBeanRegistry          	^-[#000082,plain]-  		FactoryBeanRegistrySupport
BeanFactory             								^-[#008200,plain]-      HierarchicalBeanFactory
BeanFactory                							^-[#008200,plain]-    	ListableBeanFactory
AliasRegistry                 					^-[#008200,dashed]-    	SimpleAliasRegistry
@enduml