@startuml

skinparam linetype ortho

class AbstractBeanDefinitionParser
class AbstractPropertyLoadingBeanDefinitionParser
class AbstractSingleBeanDefinitionParser
interface BeanDefinitionParser
class CatBeanDefinitionParser
class ComponentBeanDefinitionParser
class ComponentScanBeanDefinitionParser
class InterceptorsBeanDefinitionParser
class PropertyPlaceholderBeanDefinitionParser

BeanDefinitionParser                          ^-[#008200,dashed]-  AbstractBeanDefinitionParser
AbstractSingleBeanDefinitionParser            ^-[#000082,plain]-   AbstractPropertyLoadingBeanDefinitionParser
AbstractBeanDefinitionParser                  ^-[#000082,plain]-   AbstractSingleBeanDefinitionParser
AbstractSingleBeanDefinitionParser            ^-[#000082,plain]-   CatBeanDefinitionParser
AbstractBeanDefinitionParser                  ^-[#000082,plain]-   ComponentBeanDefinitionParser
BeanDefinitionParser                          ^-[#008200,dashed]-  ComponentScanBeanDefinitionParser
BeanDefinitionParser                          ^-[#008200,dashed]-  InterceptorsBeanDefinitionParser
AbstractPropertyLoadingBeanDefinitionParser   ^-[#000082,plain]-   PropertyPlaceholderBeanDefinitionParser



note top of AbstractBeanDefinitionParser
抽象类，实现了许多方便的方法和子类解析标签时必须实现的模板方法
end note
note bottom of InterceptorsBeanDefinitionParser: 解析 interceptors 标签
note left of AbstractSingleBeanDefinitionParser: 继承扩展该类，将自定义 xml 解析为单个 BeanDefinition
note left of AbstractPropertyLoadingBeanDefinitionParser:解析 <context:property- > 类型的标签
note bottom of CatBeanDefinitionParser: 自定义标签解析器
note bottom of PropertyPlaceholderBeanDefinitionParser:解析 <context:property-placeholder/>
@enduml
